# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 00:02
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accordion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.CharField(blank=True, max_length=50, null=True)),
                ('width', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('style', models.TextField(blank=True, null=True)),
                ('sections', models.ManyToManyField(blank=True, to='main.Accordion')),
            ],
        ),
    ]
