# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accordion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=50)),
                ('title_style', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('content_style', models.TextField(blank=True, default='')),
                ('width', models.CharField(blank=True, default='', max_length=50)),
                ('height', models.CharField(blank=True, default='', max_length=50)),
                ('style', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubAccordion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=50)),
                ('title_style', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('content_style', models.TextField(blank=True, default='')),
                ('width', models.CharField(blank=True, default='', max_length=50)),
                ('height', models.CharField(blank=True, default='', max_length=50)),
                ('style', models.TextField(blank=True, default='')),
                ('acordeon_padre', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Accordion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
