# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171018_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accordion',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
