# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171018_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accordion',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
