# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20171018_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAccordion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('title_style', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('contet_style', models.TextField(blank=True, null=True)),
                ('width', models.CharField(blank=True, max_length=50, null=True)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('style', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='accordion',
            name='content',
        ),
        migrations.RemoveField(
            model_name='accordion',
            name='contet_style',
        ),
        migrations.RemoveField(
            model_name='accordion',
            name='height',
        ),
        migrations.RemoveField(
            model_name='accordion',
            name='name',
        ),
        migrations.RemoveField(
            model_name='accordion',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='accordion',
            name='style',
        ),
        migrations.RemoveField(
            model_name='accordion',
            name='title',
        ),
        migrations.RemoveField(
            model_name='accordion',
            name='title_style',
        ),
        migrations.RemoveField(
            model_name='accordion',
            name='width',
        ),
    ]
