# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20171018_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='accordion',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accordion',
            name='contet_style',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accordion',
            name='height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accordion',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='accordion',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='sections', to='main.SubAccordion'),
        ),
        migrations.AddField(
            model_name='accordion',
            name='style',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accordion',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accordion',
            name='title_style',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accordion',
            name='width',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subaccordion',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
