# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20171018_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accordion',
            name='sections',
        ),
        migrations.AddField(
            model_name='accordion',
            name='suba_ccordions',
            field=models.ManyToManyField(blank=True, related_name='sub_accordions', to='main.SubAccordion'),
        ),
    ]
