# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20171018_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accordion',
            old_name='suba_ccordions',
            new_name='sub_accordions',
        ),
    ]
