# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20171018_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accordion',
            name='sub_accordions',
            field=models.ManyToManyField(blank=True, related_name='accordion_sub_accordions', to='main.SubAccordion'),
        ),
    ]
