# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 06:09
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0011_auto_20171018_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accordion',
            name='sub_accordions',
        ),
        migrations.AddField(
            model_name='subaccordion',
            name='acordeon_padre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Accordion'),
        ),
        migrations.AlterField(
            model_name='accordion',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='accordion',
            name='contet_style',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='accordion',
            name='height',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='accordion',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='accordion',
            name='style',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='accordion',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='accordion',
            name='title_style',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='accordion',
            name='width',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='subaccordion',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='subaccordion',
            name='contet_style',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='subaccordion',
            name='height',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='subaccordion',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='subaccordion',
            name='style',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='subaccordion',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='subaccordion',
            name='title_style',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='subaccordion',
            name='width',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
