# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20171018_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accordion',
            old_name='contet_style',
            new_name='content_style',
        ),
        migrations.RenameField(
            model_name='subaccordion',
            old_name='contet_style',
            new_name='content_style',
        ),
    ]
